# Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [26]:
# Importing Necessary Libraries
import numpy as np

# Task 1: Initialize an empty array with size 2X2
print("------------------------------------------------------")
print()
print("1. Initialize an empty array with size 2X2.")
print()
empty_array = np.empty((2, 2))
print(empty_array)
print()

# Task 2: Initialize an all one array with size 4X2
print("------------------------------------------------------")
print()
print("2. Initialize an all one array with size 4X2.")
print()
ones_array = np.ones((4, 2))
print(ones_array)
print()

# Task 3: Return a new array of given shape and type, filled with fill value
print("------------------------------------------------------")
print()
print("3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}")
print()
fill_value_array = np.full((3, 3), 7)
print(fill_value_array)
print()

# Task 4: Return a new array of zeros with same shape and type as a given array
print("------------------------------------------------------")
print()
print("4. Return a new array of zeros with same shape and type as a given array.")
print()
existing_array = np.array([1, 2, 3, 4])
zeros_like_array = np.zeros_like(existing_array)
print("Existing array: ", existing_array)
print("Zeros-like array: ", zeros_like_array)
print()

# Task 5: Return a new array of ones with same shape and type as a given array
print("------------------------------------------------------")
print()
print("5. Return a new array of ones with same shape and type as a given array.")
print()
ones_like_array = np.ones_like(existing_array)
print("Ones-like array: ", ones_like_array)
print()

# Task 6: Convert an existing list to a numpy array
print("------------------------------------------------------")
print()
print("6. Convert an existing list to a numpy array.")
print()
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("Array from list: ", array_from_list)

------------------------------------------------------

1. Initialize an empty array with size 2X2.

[[3.10860744e-316 0.00000000e+000]
 [4.94065646e-324 6.66947427e-310]]

------------------------------------------------------

2. Initialize an all one array with size 4X2.

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

------------------------------------------------------

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

[[7 7 7]
 [7 7 7]
 [7 7 7]]

------------------------------------------------------

4. Return a new array of zeros with same shape and type as a given array.

Existing array:  [1 2 3 4]
Zeros-like array:  [0 0 0 0]

------------------------------------------------------

5. Return a new array of ones with same shape and type as a given array.

Ones-like array:  [1 1 1 1]

------------------------------------------------------

6. Convert an existing list to a numpy array.

Array from list:  [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [27]:
# Importing Necessary Libraries
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49.
print("------------------------------------------------------")
print()
print("1. Create an array with values ranging from 10 to 49.")
print()
array_10_49 = np.arange(10, 50)
print(array_10_49)
print()

# Task 2: Create a 3X3 matrix with values ranging from 0 to 8.
print("------------------------------------------------------")
print()
print("2. Create a 3X3 matrix with values ranging from 0 to 8.")
print()
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)
print()

# Task 3: Create a 3X3 identity matrix.
print("------------------------------------------------------")
print()
print("3. Create a 3X3 identity matrix.")
print()
identity_matrix = np.eye(3)
print(identity_matrix)
print()

# Task 4: Create a random array of size 30 and find the mean of the array.
print("------------------------------------------------------")
print()
print("4. Create a random array of size 30 and find the mean of the array.")
print()
random_array = np.random.random(30)
mean_of_array = random_array.mean()
print("Random Array:", random_array)
print("Mean of the array:", mean_of_array)
print()

# Task 5: Create a 10X10 array with random values and find the minimum and maximum values.
print("------------------------------------------------------")
print()
print("5. Create a 10X10 array with random values and find the minimum and maximum values.")
print()
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("Random 10X10 Array:\n", random_array_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print()

# Task 6: Create a zero array of size 10 and replace 5th element with 1.
print("------------------------------------------------------")
print()
print("6. Create a zero array of size 10 and replace 5th element with 1.")
print()
zero_array = np.zeros(10)
zero_array[4] = 1  # Replace the 5th element (index 4) with 1
print(zero_array)
print()

# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0].
print("------------------------------------------------------")
print()
print("7. Reverse an array arr = [1, 2, 0, 0, 4, 0].")
print()
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)
print()

# Task 8: Create a 2d array with 1 on border and 0 inside.
print("------------------------------------------------------")
print()
print("8. Create a 2d array with 1 on border and 0 inside.")
print()
border_1_inside_0 = np.ones((5, 5))
border_1_inside_0[1:-1, 1:-1] = 0
print(border_1_inside_0)
print()

# Task 9: Create an 8X8 matrix and fill it with a checkerboard pattern.
print("------------------------------------------------------")
print()
print("9. Create an 8X8 matrix and fill it with a checkerboard pattern.")
print()
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

------------------------------------------------------

1. Create an array with values ranging from 10 to 49.

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

------------------------------------------------------

2. Create a 3X3 matrix with values ranging from 0 to 8.

[[0 1 2]
 [3 4 5]
 [6 7 8]]

------------------------------------------------------

3. Create a 3X3 identity matrix.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

------------------------------------------------------

4. Create a random array of size 30 and find the mean of the array.

Random Array: [0.55409108 0.52161837 0.12415386 0.9314546  0.19569308 0.66763159
 0.93843128 0.62207535 0.00566982 0.42363842 0.70521031 0.8036578
 0.16459624 0.92811926 0.60467859 0.1515939  0.57871489 0.68010803
 0.86476296 0.65830445 0.31772733 0.59821016 0.4426657  0.77229265
 0.88891302 0.69321791 0.44197828 0.14452111 0.11912135 0.4649595 ]
Mean of the array: 0.

# Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [28]:
# Importing Necessary Libraries
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
print("------------------------------------------------------")
print()
print("1. Add the two arrays (x + y):")
print()
add_arrays = np.add(x, y)
print(add_arrays)
print()

# Task 2: Subtract the two arrays
print("------------------------------------------------------")
print()
print("2. Subtract the two arrays (x - y):")
print()
subtract_arrays = np.subtract(x, y)
print(subtract_arrays)
print()

# Task 3: Multiply the array with any integers of your choice
print("------------------------------------------------------")
print()
print("3. Multiply the array x with integer 2:")
print()
multiply_array = x * 2
print(multiply_array)
print()

# Task 4: Find the square of each element of the array
print("------------------------------------------------------")
print()
print("4. Square each element of the array x:")
print()
square_array = np.square(x)
print(square_array)
print()

# Task 5: Find the dot product between: v and w; x and v; x and y
print("------------------------------------------------------")
print()
print("5. Find the dot product between:")
print("v and w:")
dot_product_v_w = np.dot(v, w)
print(dot_product_v_w)

print("x and v:")
dot_product_x_v = np.dot(x, v)
print(dot_product_x_v)

print("x and y:")
dot_product_x_y = np.dot(x, y)
print(dot_product_x_y)
print()

# Task 6: Concatenate x and y along rows, and concatenate v and w along columns
print("------------------------------------------------------")
print()
print("6. Concatenate x and y along row:")
concatenate_x_y_row = np.concatenate((x, y), axis=0)
print(concatenate_x_y_row)

print("Concatenate v and w along column:")
concatenate_v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print(concatenate_v_w_column)
print()

# Task 7: Concatenate x and v; if you get an error, observe and explain why you got the error
print("------------------------------------------------------")
print()
print("7. Concatenate x and v:")
try:
    concatenate_x_v = np.concatenate((x, v), axis=0)
    print(concatenate_x_v)
except Exception as e:
    print("Error:", e)
    print("Explanation: Concatenating x and v along axis 0 gives an error because x is a 2D array (shape 2x2) and v is a 1D array (shape 2). The dimensions do not align for concatenation.")

------------------------------------------------------

1. Add the two arrays (x + y):

[[ 6  8]
 [10 13]]

------------------------------------------------------

2. Subtract the two arrays (x - y):

[[-4 -4]
 [-4 -3]]

------------------------------------------------------

3. Multiply the array x with integer 2:

[[ 2  4]
 [ 6 10]]

------------------------------------------------------

4. Square each element of the array x:

[[ 1  4]
 [ 9 25]]

------------------------------------------------------

5. Find the dot product between:
v and w:
219
x and v:
[29 77]
x and y:
[[19 22]
 [50 58]]

------------------------------------------------------

6. Concatenate x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 11]
 [10 12]]

------------------------------------------------------

7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimen

# Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1
= I.
2. Prove AB ̸= BA.
3. Prove (AB)T
= BT AT
.
• Solve the following system of Linear equation using Inverse Methods.
2x−3y + z =−1
x−y + 2z =−3
3x + y−z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX= B}
• Now: solve the abo

In [29]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A^(-1) = I (Identity matrix)
print("------------------------------------------------------")
print()
print("1. Prove A.A^(-1) = I:")
print()
A_inv = np.linalg.inv(A)  # Inverse of A
identity_matrix = np.dot(A, A_inv)
print("A.A^(-1):")
print(identity_matrix)
print("Identity Matrix I:")
print(np.eye(2))  # Identity matrix for comparison
print()

# Task 2: Prove AB != BA
print("------------------------------------------------------")
print()
print("2. Prove AB != BA:")
print()
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))
print()

# Task 3: Prove (AB)^T = B^T A^T
print("------------------------------------------------------")
print()
print("3. Prove (AB)^T = B^T A^T:")
print()
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("Transpose of AB:")
print(AB_T)
print("B^T A^T:")
print(BT_AT)
print("Are (AB)^T and B^T A^T equal?", np.array_equal(AB_T, BT_AT))
print()

# Task 4: Solve the system of linear equations using inverse method
print("------------------------------------------------------")
print()
print("4. Solve the system of linear equations using inverse method:")

# The system of equations is:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
#
# Matrix form is AX = B
# A = [[2, -3, 1], [1, -1, 2], [3, 1, -1]]
# B = [-1, -3, 9]

A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix
B_matrix = np.array([-1, -3, 9])  # Right-hand side matrix

# Solve for X (x, y, z)
X = np.linalg.solve(A_matrix, B_matrix)
print("Solution (x, y, z):")
print(X)

------------------------------------------------------

1. Prove A.A^(-1) = I:

A.A^(-1):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix I:
[[1. 0.]
 [0. 1.]]

------------------------------------------------------

2. Prove AB != BA:

AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are AB and BA equal? False

------------------------------------------------------

3. Prove (AB)^T = B^T A^T:

Transpose of AB:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]
Are (AB)^T and B^T A^T equal? True

------------------------------------------------------

4. Solve the system of linear equations using inverse method:
Solution (x, y, z):
[ 2.  1. -2.]
